### ISSUE TITLE
os6_facts error when processing neighbors and config is empty

### ISSUE THREAD

**Issue by Yannis100** [ansible-collections/dellemc.os6#38]
##### SUMMARY
os6_facts error when processing neighbors
Working well when restricting subset gathering (!interfaces)
But even so the config and hostname vars are empty; note that the config takes few seconds to show (quite big) when running the command on the switch

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
os6_facts.py

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.3]
  config file = /home/admin/ansible/ansible/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/admin/.local/bin/ansible
  python version = 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION
```paste below
# /home/admin/.local/lib/python3.8/site-packages/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7

# /home/admin/.ansible/collections/ansible_collections
Collection  Version
----------- -------
dellemc.os6 1.0.7
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/home/admin/ansible/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/admin/ansible/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/admin/ansible/ansible/ansible.cfg) = cache
CACHE_PLUGIN_TIMEOUT(/home/admin/ansible/ansible/ansible.cfg) = 3600
DEFAULT_FORKS(/home/admin/ansible/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/home/admin/ansible/ansible/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/home/admin/ansible/ansible/ansible.cfg) = ['!config', '!hardware', '!interfaces']
DEFAULT_HOST_LIST(/home/admin/ansible/ansible/ansible.cfg) = ['/home/admin/ansible/ansible/inventory']
DEFAULT_VAULT_PASSWORD_FILE(/home/admin/ansible/ansible/ansible.cfg) = /home/admin/ansible/ansible/.vault-pass
HOST_KEY_CHECKING(/home/admin/ansible/ansible/ansible.cfg) = False
INVENTORY_CACHE_ENABLED(/home/admin/ansible/ansible/ansible.cfg) = True
INVENTORY_CACHE_TIMEOUT(/home/admin/ansible/ansible/ansible.cfg) = 3600
INVENTORY_ENABLED(/home/admin/ansible/ansible/ansible.cfg) = ['auto', 'ini', 'yaml', 'netbox.netbox.nb_inventory']
```

##### OS / ENVIRONMENT

Linux 5.4.0-77-generic #86-Ubuntu

##### STEPS TO REPRODUCE

```yaml
---
- hosts: import
  gather_facts: no
  collections:
    - dellemc.os6
  tasks:
    - name: facts
      os6_facts:
        gather_subset: all
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 100, in <module>
  File "<stdin>", line 92, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py", line 478, in <module>
  File "/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py", line 463, in main
  File "/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py", line 232, in populate
  File "/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py", line 281, in parse_neighbors
ValueError: not enough values to unpack (expected 2, got 1)
fatal: [sw-asca]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 100, in <module>\n  File \"<stdin>\", line 92, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py\", line 478, in <module>\n  File \"/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py\", line 463, in main\n  File \"/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py\", line 232, in populate\n  File \"/tmp/ansible_os6_facts_payload_q684hvka/ansible_os6_facts_payload.zip/ansible_collections/dellemc/os6/plugins/modules/os6_facts.py\", line 281, in parse_neighbors\nValueError: not enough values to unpack (expected 2, got 1)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
Without interfaces :
```
ok: [sw-asca] => {
    "ansible_facts": {
        "ansible_net_config": "",
        "ansible_net_gather_subset": [
            "hardware",
            "default",
            "config"
        ],
        "ansible_net_hostname": null,
        "ansible_net_image": "N2000Stdv6.6.3",
        "ansible_net_model": "N2024",
        "ansible_net_serialnum": "CN0P8K2F2826813L0161A09",
        "ansible_net_version": {
            "Version": [
                {
                    "HW Version": "5",
                    "SW Version": "6.6.3.0"
                }
            ]
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "!interfaces"
            ],
            "provider": null
        }
    }
}

```

https://github.com/ansible-collections/dellemc.os6/blob/b1a3d3d14411dd454cb4db978e4f6bcdf7862f8b/plugins/modules/os6_facts.py#L232

An OS6.6.3.0 output for reference :
```
SW#show lldp remote-device all

LLDP Remote Device Summary

Local
Interface RemID   Chassis ID          Port ID           System Name
--------- ------- ------------------- ----------------- ------------------
Gi4/0/3   23      172.16.0.1       00:FA:E8:7E:BC:7F
Gi4/0/4   95      172.16.0.2       00:FA:E8:7E:B8:8F
Gi4/0/7   26      172.16.0.3       00:FA:E8:7F:20:41
Gi4/0/10  175     172.16.0.4       00:FA:E8:7F:20:5D
```

**Comment by Yannis100** [comment]
Found that the command output on the switch has 1 more '-' than on line 281 (parse_neighbors) : https://github.com/ansible-collections/dellemc.os6/blob/b1a3d3d14411dd454cb4db978e4f6bcdf7862f8b/plugins/modules/os6_facts.py#L281
Not 100% sure it's relevant, I'll try to edit the line and see

**Comment by Yannis100** [comment]
My bad, forgot to set ansible_become: yes
ansible_become_method: enable
